=== NingMoe/product.manger/src/main/resources/navigation.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.phicomm.com/XMLSchema"
            xmlns="http://www.phicomm.com/XMLSchema"
            elementFormDefault="qualified">

    <xsd:annotation>
        <xsd:documentation>
            <![CDATA[
	Defines the elements used in the main_layout navigation.
		]]>
        </xsd:documentation>
    </xsd:annotation>

    <xsd:element name="id">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:minLength value="1"/>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:element name="title-name" type="xsd:string"/>
    <xsd:element name="title-description" type="xsd:string"/>

    <xsd:element name="title">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="title-name"/>
                <xsd:element ref="title-description"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="icon" type="xsd:string"/>
    <xsd:element name="name" type="xsd:string"/>
    <xsd:element name="url" type="xsd:string"/>
    <xsd:element name="sub-directories">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="name" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="directory">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="icon"/>
                <xsd:element ref="name"/>
                <xsd:element ref="url"/>
                <xsd:element ref="sub-directories"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="navigation">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="id"/>
                <xsd:element ref="title"/>
                <xsd:element ref="directory"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="navigations">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="navigation" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== NingMoe/product.manger/src/main/resources/navigation.xml
<?xml version="1.0" encoding="UTF-8" ?>
<navigations xmlns="http://www.phicomm.com/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.phicomm.com/XMLSchema navigation.xsd">

    <navigation>
        <id>homepage</id>
        <title>
            <title-name>首页</title-name>
            <title-description>首页</title-description>
        </title>
        <directory>
            <icon>fa fa-dashboard</icon>
            <name>Home</name>
            <url>$baseUrl/homepage</url>
            <sub-directories>
                <name>homepage</name>
            </sub-directories>
        </directory>
    </navigation>

    <navigation>
        <id>permissionManger</id>
        <title>
            <title-name>权限管理</title-name>
            <title-description>权限管理</title-description>
        </title>
        <directory>
            <icon>fa fa-dashboard</icon>
            <name>Home</name>
            <url>$baseUrl/permission</url>
            <sub-directories>
                <name>permission</name>
            </sub-directories>
        </directory>
    </navigation>

    <navigation>
        <id>salesLocationStatistic</id>
        <title>
            <title-name>统计</title-name>
            <title-description>体脂秤激活地理位置统计</title-description>
        </title>
        <directory>
            <icon>fa fa-dashboard</icon>
            <name>Home</name>
            <url>$baseUrl/statistic/sales/location</url>
            <sub-directories>
                <name>salesLocationStatistic</name>
            </sub-directories>
        </directory>
    </navigation>

    <navigation>
        <id>balanceStatisticKCodeActive</id>
        <title>
            <title-name>统计</title-name>
            <title-description>体脂秤K码激活统计</title-description>
        </title>
        <directory>
            <icon>fa fa-dashboard</icon>
            <name>Home</name>
            <url>$baseUrl/balance/statistic/page/k/code/active</url>
            <sub-directories>
                <name>BalanceStatisticKCodeActive</name>
            </sub-directories>
        </directory>
    </navigation>

</navigations>
