=== NingMoe/product.manger/src/main/resources/permission.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.phicomm.com/XMLSchema"
            xmlns="http://www.phicomm.com/XMLSchema"
            elementFormDefault="qualified">

    <xsd:element name="id">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:minLength value="1"/>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="name">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:minLength value="1"/>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="description">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:minLength value="1"/>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="permission">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="id"/>
                <xsd:element ref="name"/>
                <xsd:element ref="description"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="common-permission">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="permission" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="permissions">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="permission" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="permission-manager">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="common-permission" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="permissions" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== NingMoe/product.manger/src/main/resources/permission.xml
<?xml version="1.0" encoding="utf-8" ?>
<permission-manager xmlns="http://www.phicomm.com/XMLSchema"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.phicomm.com/XMLSchema permission.xsd">

    <!-- 公共权限 -->
    <common-permission>
        <permission>
            <id>common</id>
            <name>common</name>
            <description>接口只要登录就可以访问的权限</description>
        </permission>
    </common-permission>

    <!-- 特定权限 -->
    <permissions>
        <permission>
            <id>permissionManger</id>
            <name>权限管理</name>
            <description>整个的权限控制，只允许admin用户拥有该权限</description>
        </permission>
        <permission>
            <id>balanceManger</id>
            <name>电子秤升级管理</name>
            <description>包括电子秤mcu升级、wifi固件升级等操作等相关权限</description>
        </permission>
        <permission>
            <id>feedbackManger</id>
            <name>用户意见反馈管理</name>
            <description>用户意见反馈管理等相关权限</description>
        </permission>
    </permissions>

</permission-manager>
